#!/usr/bin/env bash
set -euo pipefail

mode="${1:---write}"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="$root/crates/pi-bridge-types/bindings"
actual_bindings="$root/node/src/generated/bindings"
actual_barrel="$root/node/src/generated/protocol.ts"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
expected_bindings="$tmp/bindings"
expected_barrel="$tmp/protocol.ts"

mkdir -p "$expected_bindings"
cp -R "$src"/. "$expected_bindings"/

while IFS= read -r -d '' file; do
	python - "$file" <<'PY'
from pathlib import Path
import re
import sys
path = Path(sys.argv[1])
text = path.read_text()
text = re.sub(r'from "(\.[^"]*)";', r'from "\1.js";', text)
path.write_text(text)
PY
done < <(find "$expected_bindings" -type f -name '*.ts' -print0)

{
	echo "// This file was generated by scripts/sync-protocol.sh. Do not edit manually."
	echo
	while IFS= read -r file; do
		rel="${file#"$expected_bindings/"}"
		name="$(basename "$rel" .ts)"
		path="./bindings/${rel%.ts}.js"
		echo "export type { $name } from \"$path\";"
	done < <(find "$expected_bindings" -type f -name '*.ts' | sort)
} >"$expected_barrel"

case "$mode" in
--write | write)
	rm -rf "$actual_bindings"
	mkdir -p "$(dirname "$actual_barrel")"
	cp -R "$expected_bindings" "$actual_bindings"
	cp "$expected_barrel" "$actual_barrel"
	;;
--check | check)
	if ! diff -ru "$expected_bindings" "$actual_bindings"; then
		echo "Generated protocol bindings are out of sync. Run scripts/sync-protocol.sh --write" >&2
		exit 1
	fi
	if ! cmp -s "$expected_barrel" "$actual_barrel"; then
		diff -u "$expected_barrel" "$actual_barrel" || true
		echo "Generated protocol barrel is out of sync. Run scripts/sync-protocol.sh --write" >&2
		exit 1
	fi
	;;
*)
	echo "usage: $0 [--write|--check]" >&2
	exit 2
	;;
esac
