// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutocompleteItem = { label: string, detail: string | null, replacement: string | null, };
