// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeResponsePayload } from "./BridgeResponsePayload";
import type { RequestId } from "./RequestId";

export type BridgeResponseEnvelope = { version: number, requestId: RequestId, response: BridgeResponsePayload, };
