// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeError } from "./BridgeError";
import type { BridgeResponse } from "./BridgeResponse";

export type BridgeResponsePayload = { "status": "ok", value: BridgeResponse, } | { "status": "error", error: BridgeError, };
