// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeError } from "./BridgeError";
import type { ComponentRenderRequest } from "./ComponentRenderRequest";
import type { CoreStateSnapshot } from "./CoreStateSnapshot";
import type { Diagnostic } from "./Diagnostic";
import type { ExtensionUiRequest } from "./ExtensionUiRequest";
import type { ExtensionUiUpdate } from "./ExtensionUiUpdate";
import type { LogEvent } from "./LogEvent";
import type { QueueSnapshot } from "./QueueSnapshot";
import type { ReadyEvent } from "./ReadyEvent";
import type { JsonValue } from "./serde_json/JsonValue";

export type BridgeEvent = { "type": "ready", "payload": ReadyEvent } | { "type": "log", "payload": LogEvent } | { "type": "fatalError", "payload": { error: BridgeError, } } | { "type": "diagnostics", "payload": { diagnostics: Array<Diagnostic>, } } | { "type": "stateSnapshot", "payload": { state: CoreStateSnapshot, } } | { "type": "piSessionEvent", "payload": { event: JsonValue, } } | { "type": "queueUpdate", "payload": { queue: QueueSnapshot, } } | { "type": "bashChunk", "payload": { chunk: string, } } | { "type": "extensionUiRequest", "payload": { request: ExtensionUiRequest, } } | { "type": "extensionUiUpdate", "payload": { update: ExtensionUiUpdate, } } | { "type": "componentRenderRequest", "payload": { request: ComponentRenderRequest, } } | { "type": "shutdown" };
