// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeEvent } from "./BridgeEvent";

export type BridgeEventEnvelope = { version: number, event: BridgeEvent, };
