// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeCommand } from "./BridgeCommand";
import type { RequestId } from "./RequestId";

export type BridgeCommandEnvelope = { version: number, requestId: RequestId, command: BridgeCommand, };
