// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutocompleteItem } from "./AutocompleteItem";
import type { ComponentRenderResult } from "./ComponentRenderResult";
import type { CoreStateSnapshot } from "./CoreStateSnapshot";
import type { ModelDescriptor } from "./ModelDescriptor";
import type { ProviderAuthStatus } from "./ProviderAuthStatus";
import type { ToolDescriptor } from "./ToolDescriptor";
import type { JsonValue } from "./serde_json/JsonValue";

export type BridgeResponse = { "type": "ack" } | { "type": "state", "payload": { state: CoreStateSnapshot, } } | { "type": "messages", "payload": { messages: Array<JsonValue>, } } | { "type": "sessionStats", "payload": { stats: JsonValue, } } | { "type": "authStatus", "payload": { statuses: Array<ProviderAuthStatus>, } } | { "type": "models", "payload": { models: Array<ModelDescriptor>, } } | { "type": "tools", "payload": { tools: Array<ToolDescriptor>, } } | { "type": "path", "payload": { path: string, } } | { "type": "text", "payload": { text: string, } } | { "type": "json", "payload": { value: JsonValue, } } | { "type": "cancelled", "payload": { cancelled: boolean, } } | { "type": "autocomplete", "payload": { items: Array<AutocompleteItem>, } } | { "type": "componentRender", "payload": { render: ComponentRenderResult, } };
