// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentHandleId } from "./ComponentHandleId";
import type { RequestId } from "./RequestId";

export type ComponentRenderRequest = { requestId: RequestId, handle: ComponentHandleId, width: number, };
