// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentHandleId } from "./ComponentHandleId";

export type ComponentContent = { "type": "lines", "payload": { lines: Array<string>, } } | { "type": "handle", "payload": { handle: ComponentHandleId, } };
