// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiRequestId } from "./UiRequestId";

export type ConfirmRequest = { id: UiRequestId, title: string, message: string, timeoutMs: number | null, };
