// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeliveryMode } from "./DeliveryMode";
import type { JsonValue } from "./serde_json/JsonValue";

export type CustomMessageCommand = { customType: string, content: JsonValue, display: boolean, details: JsonValue | null, triggerTurn: boolean, deliverAs: DeliveryMode | null, };
