// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentHandleId } from "./ComponentHandleId";
import type { UiRequestId } from "./UiRequestId";
import type { JsonValue } from "./serde_json/JsonValue";

export type CustomComponentRequest = { id: UiRequestId, handle: ComponentHandleId, overlay: boolean, overlayOptions: JsonValue | null, };
