// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutocompleteRequest } from "./AutocompleteRequest";
import type { ConfirmRequest } from "./ConfirmRequest";
import type { CustomComponentRequest } from "./CustomComponentRequest";
import type { EditorRequest } from "./EditorRequest";
import type { InputRequest } from "./InputRequest";
import type { SelectRequest } from "./SelectRequest";

export type ExtensionUiRequest = { "type": "select", "payload": SelectRequest } | { "type": "confirm", "payload": ConfirmRequest } | { "type": "input", "payload": InputRequest } | { "type": "editor", "payload": EditorRequest } | { "type": "customComponent", "payload": CustomComponentRequest } | { "type": "autocomplete", "payload": AutocompleteRequest };
