// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutocompleteItem } from "./AutocompleteItem";
import type { JsonValue } from "./serde_json/JsonValue";

export type ExtensionUiResponse = { "type": "selected", "payload": { value: string | null, } } | { "type": "confirmed", "payload": { value: boolean, } } | { "type": "text", "payload": { value: string | null, } } | { "type": "custom", "payload": { value: JsonValue, } } | { "type": "autocomplete", "payload": { items: Array<AutocompleteItem>, } } | { "type": "cancelled" };
