// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentSlotUpdate } from "./ComponentSlotUpdate";
import type { NotifyUpdate } from "./NotifyUpdate";
import type { StatusUpdate } from "./StatusUpdate";
import type { WidgetUpdate } from "./WidgetUpdate";
import type { WorkingUpdate } from "./WorkingUpdate";
import type { JsonValue } from "./serde_json/JsonValue";

export type ExtensionUiUpdate = { "type": "notify", "payload": NotifyUpdate } | { "type": "status", "payload": StatusUpdate } | { "type": "working", "payload": WorkingUpdate } | { "type": "widget", "payload": WidgetUpdate } | { "type": "footer", "payload": ComponentSlotUpdate } | { "type": "header", "payload": ComponentSlotUpdate } | { "type": "title", "payload": { title: string, } } | { "type": "editorText", "payload": { text: string, } } | { "type": "theme", "payload": { theme: JsonValue, } } | { "type": "toolsExpanded", "payload": { expanded: boolean, } };
