// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelSelection } from "./ModelSelection";
import type { SessionTarget } from "./SessionTarget";
import type { TestModeConfig } from "./TestModeConfig";

export type InitCommand = { cwd: string, agentDir: string | null, session: SessionTarget | null, model: ModelSelection | null, tools: Array<string> | null, enableExtensions: boolean, testMode: TestModeConfig | null, };
