// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageScope } from "./PackageScope";

export type InstalledPackage = { source: string, displayName: string, scope: PackageScope, filtered: boolean, installedPath: string | null, version: string | null, description: string | null, };
