// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageCanvasNodeRenderMode } from "./PackageCanvasNodeRenderMode";
import type { PackageCanvasNodeRuntime } from "./PackageCanvasNodeRuntime";

export type PackageCanvasNodeManifest = { id: string, label: string, runtime: PackageCanvasNodeRuntime, renderMode: PackageCanvasNodeRenderMode, };
