// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageAttachment } from "./ImageAttachment";
import type { StreamingBehavior } from "./StreamingBehavior";

export type PromptCommand = { sessionPath: string | null, text: string, images: Array<ImageAttachment>, streamingBehavior: StreamingBehavior | null, };
