// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadyEvent = { nodeVersion: string, piVersion: string | null, protocolVersion: number, };
