// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionTarget = { "type": "new" } | { "type": "continueRecent" } | { "type": "open", "payload": { path: string, } };
