// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionUiResponse } from "./ExtensionUiResponse";
import type { UiRequestId } from "./UiRequestId";

export type UiResponseCommand = { requestId: UiRequestId, response: ExtensionUiResponse, };
