// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentContent } from "./ComponentContent";
import type { WidgetPlacement } from "./WidgetPlacement";

export type WidgetUpdate = { key: string, placement: WidgetPlacement, content: ComponentContent | null, };
